// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(DbContextCodeCar))]
    [Migration("20230412175235_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Entities.CarNumberCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("CarNumberCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BK",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "HK",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "AC",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "KC",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "AM",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "KM",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "BC",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 8,
                            Code = "HC",
                            RegionId = 4
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameRegion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameRegion = "Рівненська"
                        },
                        new
                        {
                            Id = 2,
                            NameRegion = "Волинська"
                        },
                        new
                        {
                            Id = 3,
                            NameRegion = "Житомирська"
                        },
                        new
                        {
                            Id = 4,
                            NameRegion = "Львівська"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.CarNumberCode", b =>
                {
                    b.HasOne("DataAccess.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
